/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adminFunctions;

/**
 *
 * @author Hoang Ha My
 */
public class AdminFunction_form extends javax.swing.JFrame {

    /**
     * Creates new form adminFunction_form
     */
    public AdminFunction_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteVanContract1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        addCarButton = new javax.swing.JButton();
        deleteCarButton = new javax.swing.JButton();
        addVanButton = new javax.swing.JButton();
        deleteVanButton = new javax.swing.JButton();
        updateCarButton = new javax.swing.JButton();
        updateVanButton = new javax.swing.JButton();
        searchContractButton = new javax.swing.JButton();
        searchVehicleButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        calculateProceedsButton = new javax.swing.JButton();

        deleteVanContract1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deleteVanContract1.setForeground(new java.awt.Color(255, 51, 51));
        deleteVanContract1.setText("4. Delete Van Parking Contract");
        deleteVanContract1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVanContract1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("PARKING MANAGEMENT SYSTEM");

        addCarButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addCarButton.setForeground(new java.awt.Color(255, 51, 51));
        addCarButton.setText("Add Car Parking Contract");
        addCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarButtonActionPerformed(evt);
            }
        });

        deleteCarButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deleteCarButton.setForeground(new java.awt.Color(255, 51, 51));
        deleteCarButton.setText("Delete Car Parking Contract");
        deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarButtonActionPerformed(evt);
            }
        });

        addVanButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addVanButton.setForeground(new java.awt.Color(255, 51, 51));
        addVanButton.setText("Add Van Parking Contract");
        addVanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVanButtonActionPerformed(evt);
            }
        });

        deleteVanButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deleteVanButton.setForeground(new java.awt.Color(255, 51, 51));
        deleteVanButton.setText("Delete Van Parking Contract");
        deleteVanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVanButtonActionPerformed(evt);
            }
        });

        updateCarButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        updateCarButton.setForeground(new java.awt.Color(255, 51, 51));
        updateCarButton.setText("Update Car Parking Contract");
        updateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarButtonActionPerformed(evt);
            }
        });

        updateVanButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        updateVanButton.setForeground(new java.awt.Color(255, 51, 51));
        updateVanButton.setText("Update Van Parking Contract");
        updateVanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVanButtonActionPerformed(evt);
            }
        });

        searchContractButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        searchContractButton.setForeground(new java.awt.Color(255, 51, 51));
        searchContractButton.setText("Search For Contracts");
        searchContractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchContractButtonActionPerformed(evt);
            }
        });

        searchVehicleButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        searchVehicleButton.setForeground(new java.awt.Color(255, 51, 51));
        searchVehicleButton.setText("Search For Vehicle By Fee");
        searchVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVehicleButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 51, 51));
        updateButton.setText("Update Fees And Offer");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        calculateProceedsButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        calculateProceedsButton.setForeground(new java.awt.Color(255, 51, 51));
        calculateProceedsButton.setText("CALCULATE PROCEEDS");
        calculateProceedsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateProceedsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(248, 248, 248))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateCarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculateProceedsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateVanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteVanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addVanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchContractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchContractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteVanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateVanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(calculateProceedsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        // TODO add your handling code here:
        new DeleteCarContract_form().setVisible(true);
        dispose();
    }//GEN-LAST:event_deleteCarButtonActionPerformed

    private void addVanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVanButtonActionPerformed
        // TODO add your handling code here:
        new AddVanContract_form().setVisible(true);
        dispose();
    }//GEN-LAST:event_addVanButtonActionPerformed

    private void deleteVanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVanButtonActionPerformed
        // TODO add your handling code here:
        new DeleteVanContract_form().setVisible(true);
        dispose();
    }//GEN-LAST:event_deleteVanButtonActionPerformed

    private void deleteVanContract1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVanContract1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteVanContract1ActionPerformed

    private void updateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarButtonActionPerformed
        // TODO add your handling code here:
        new UpdateCarContract_form().setVisible(true);
        dispose();
    }//GEN-LAST:event_updateCarButtonActionPerformed

    private void updateVanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVanButtonActionPerformed
        // TODO add your handling code here:
        new UpdateVanContract_form().setVisible(true);
        dispose();
    }//GEN-LAST:event_updateVanButtonActionPerformed

    private void searchContractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchContractButtonActionPerformed
        // TODO add your handling code here:
        new  SearchContract_form().setVisible(true);
    }//GEN-LAST:event_searchContractButtonActionPerformed

    private void searchVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVehicleButtonActionPerformed
        // TODO add your handling code here:
        new SearchContractByFee_form().setVisible(true);
    }//GEN-LAST:event_searchVehicleButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        new UpdateFeeAndOffer_form().setVisible(true);
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void calculateProceedsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateProceedsButtonActionPerformed
        // TODO add your handling code here:
        new CalculateProceed_form().setVisible(true);
    }//GEN-LAST:event_calculateProceedsButtonActionPerformed

    private void addCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarButtonActionPerformed
        // TODO add your handling code here:
        new AddCarContract_form().setVisible(true);
        dispose();
    }//GEN-LAST:event_addCarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFunction_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFunction_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFunction_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFunction_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFunction_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarButton;
    private javax.swing.JButton addVanButton;
    private javax.swing.JButton calculateProceedsButton;
    private javax.swing.JButton deleteCarButton;
    private javax.swing.JButton deleteVanButton;
    private javax.swing.JButton deleteVanContract1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JButton searchContractButton;
    private javax.swing.JButton searchVehicleButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateCarButton;
    private javax.swing.JButton updateVanButton;
    // End of variables declaration//GEN-END:variables
}
